// Індивідуальні описи для кожної карти Молодших Арканів
// Порядок: Туз, 2, 3, 4, 5, 6, 7, 8, 9, 10, Паж, Лицар, Королева, Король

const minorArcanaDescriptions = {

    // ── ЖЕЗЛИ (Вогонь) ───────────────────────────────────────────────────────
    w: [
        { upright: 'Початок нового проєкту, приплив сильної енергії, пристрасть, натхнення. Шанс, який дає доля.', upright_en: 'The beginning of a new project, a surge of powerful energy, passion, and inspiration. A chance given by fate.', reversed: 'Затримки старту, брак енергії, творча криза або невчасно реалізована ідея.', reversed_en: 'Delays at the start, lack of energy, creative crisis, or an idea realized at the wrong time.' },
        { upright: 'Людина стоїть на роздоріжжі, оцінює свої сили та будує плани на майбутнє. Період роздумів перед дією.', upright_en: 'A person stands at a crossroads, assessing their strength and making plans for the future. A period of reflection before action.', reversed: 'Страх зробити крок, надмірна обережність або очікування без руху вперед.', reversed_en: 'Fear of taking a step, excessive caution, or waiting without moving forward.' },
        { upright: 'Надійний фундамент закладено, перші результати вже видно. Карта впевненості, успішного співробітництва та розширення горизонтів.', upright_en: 'A solid foundation has been laid and the first results are already visible. A card of confidence, successful cooperation, and expanding horizons.', reversed: 'Затримки у справах, невдале партнерство або невміння делегувати.', reversed_en: 'Delays in matters, failed partnerships, or an inability to delegate.' },
        { upright: 'Одна з найпозитивніших карт. Символізує свято, відпочинок, безпеку, повернення додому, успішне завершення етапу.', upright_en: 'One of the most positive cards. Symbolizes celebration, rest, safety, returning home, and the successful completion of a phase.', reversed: 'Відкладений відпочинок, нестабільність у домівці або зірване свято.', reversed_en: 'Delayed rest, instability at home, or a ruined celebration.' },
        { upright: 'Боротьба амбіцій, суперечки, внутрішній або зовнішній конфлікт. Це не ворожнеча, а скоріше перевірка сил, брейншторм або критика.', upright_en: 'A clash of ambitions, arguments, internal or external conflict. This is not hostility, but rather a test of strength, brainstorming, or criticism.', reversed: 'Уникнення конфлікту, капітуляція або хаос без мети.', reversed_en: 'Avoiding conflict, capitulation, or purposeless chaos.' },
        { upright: 'Карта переможця. Ви отримуєте заслужену славу, лідерство, публічний успіх. Ваші досягнення визнають інші.', upright_en: 'The card of the winner. You receive well-deserved fame, leadership, and public success. Your achievements are recognized by others.', reversed: 'Марнославство, нестабільна популярність або падіння з вершини.', reversed_en: 'Vanity, unstable popularity, or a fall from the top.' },
        { upright: 'Вам доводиться захищати свої позиції чи переконання від нападків ззовні. Ви перебуваєте в меншості, але маєте всі шанси встояти.', upright_en: 'You must defend your position or beliefs from outside attacks. You are in the minority, but have every chance of holding your ground.', reversed: 'Виснаження від постійної боротьби, нездатність дати відсіч або поразка.', reversed_en: 'Exhaustion from constant struggle, inability to fight back, or defeat.' },
        { upright: 'Події розвиваються стрімко. Карта означає термінові звістки, телефонні дзвінки, інтернет-комунікацію або швидкі поїздки (перельоти).', upright_en: 'Events are developing rapidly. The card signifies urgent news, phone calls, internet communication, or swift trips (flights).', reversed: 'Затримки, скасовані плани або інформація, яка запізнюється.', reversed_en: 'Delays, cancelled plans, or information that arrives too late.' },
        { upright: 'Людина готова до труднощів через минулі помилки. Карта означає настороженість, захист особистих кордонів, очікування підвоху.', upright_en: 'A person is prepared for difficulties due to past mistakes. The card signifies vigilance, protecting personal boundaries, and anticipating a catch.', reversed: 'Параноя, хронічна підозрілість або нездатність довіряти людям.', reversed_en: 'Paranoia, chronic suspicion, or an inability to trust people.' },
        { upright: 'Ви взяли на себе занадто багато відповідальності чи обов\'язків. Успіх досягнутий, але ціна за нього — повне вигорання та перевантаження.', upright_en: 'You have taken on too much responsibility or obligations. Success has been achieved, but the price is complete burnout and overload.', reversed: 'Скидання зайвого тягаря, делегування або відмова від непосильної ноші.', reversed_en: 'Shedding excess burdens, delegating, or refusing an unbearable load.' },
        { upright: 'Молода енергія. Вісник, який приносить гарні новини чи пропозиції. Також символізує початок навчання або творчий імпульс.', upright_en: 'Young energy. A messenger who brings good news or proposals. It also symbolizes the start of learning or a creative impulse.', reversed: 'Порожні обіцянки, затримка новин або нереалізований ентузіазм.', reversed_en: 'Empty promises, delayed news, or unrealized enthusiasm.' },
        { upright: 'Стрімка дія, енергійність, часом імпульсивність та егоїзм. Карта подорожей, зміни місця проживання або бурхливих стосунків.', upright_en: 'Swift action, energy, sometimes impulsiveness and selfishness. A card of travel, changing residence, or turbulent relationships.', reversed: 'Непередбачуваність, ризикова поведінка або конфлікти через поспіх.', reversed_en: 'Unpredictability, risky behavior, or conflicts due to haste.' },
        { upright: 'Яскрава, незалежна, оптимістична жінка. Вона знає, чого хоче, керує своїм життям, має сильне магнетичне приваблення.', upright_en: 'A bright, independent, optimistic woman. She knows what she wants, is in control of her life, and has a strong magnetic attraction.', reversed: 'Надмірна вимогливість, ревнощі або втрата впевненості в собі.', reversed_en: 'Excessive demandingness, jealousy, or a loss of self-confidence.' },
        { upright: 'Зрілий, харизматичний чоловік із палкою вдачею. Підприємець, керівник, захисник. Карта уособлює волю, масштабні проєкти та владу.', upright_en: 'A mature, charismatic man with a fiery nature. An entrepreneur, leader, and protector. The card embodies will, large-scale projects, and authority.', reversed: 'Авторитаризм, вибуховий характер або зловживання владою.', reversed_en: 'Authoritarianism, explosive temper, or an abuse of power.' }
    ],

    // ── КУБКИ (Вода) ─────────────────────────────────────────────────────────
    c: [
        { upright: 'Початок закоханості, щира радість, гармонія, творче натхнення. Наповненість щастям.', upright_en: 'The beginning of falling in love, sincere joy, harmony, creative inspiration. Filled with happiness.', reversed: 'Пригнічені емоції, нереалізований творчий потенціал або порожнеча всередині.', reversed_en: 'Suppressed emotions, unrealized creative potential, or inner emptiness.' },
        { upright: 'Романтичне побачення, взаємне кохання, укладання вигідного миру чи союзу, взаєморозуміння.', upright_en: 'A romantic date, mutual love, forming a beneficial peace or union, and mutual understanding.', reversed: 'Дисбаланс у стосунках, розрив домовленостей або нерозділена любов.', reversed_en: 'Imbalance in a relationship, breaking of agreements, or unrequited love.' },
        { upright: 'Вечірка, радісна подія у колі друзів чи родини. Святкування успіху, підтримка близьких.', upright_en: 'A party, a joyful event among friends or family. Celebrating success and support from loved ones.', reversed: 'Надмірні гуляння, поверхнева дружба або ізоляція від соціуму.', reversed_en: 'Excessive merrymaking, superficial friendships, or social isolation.' },
        { upright: 'Емоційне вигорання, апатія. Людина не помічає нових шансів, бо зациклена на своєму смутку.', upright_en: 'Emotional burnout, apathy. A person does not notice new opportunities because they are fixated on their sadness.', reversed: 'Вихід із депресії, нова мотивація або усвідомлення пропущених можливостей.', reversed_en: 'Emerging from depression, new motivation, or awareness of missed opportunities.' },
        { upright: 'Розчарування, жаль за минулим. Проте карта нагадує: втрачено не все, позаду є ще повні кубки.', upright_en: 'Disappointment, regret for the past. However, the card reminds us: not everything is lost, there are still full cups behind you.', reversed: 'Прийняття втрати, рух уперед або відпускання болю.', reversed_en: 'Acceptance of loss, moving forward, or letting go of pain.' },
        { upright: 'Повернення до минулого, зустріч зі старими друзями, дитячі спогади. Карта тепла і затишку.', upright_en: 'A return to the past, meeting old friends, and childhood memories. A card of warmth and coziness.', reversed: 'Нездорова ностальгія, нездатність жити сьогоденням або болісне минуле.', reversed_en: 'Unhealthy nostalgia, an inability to live in the present, or a painful past.' },
        { upright: 'Великий вибір, але більшість варіантів — обман чи фантазії. Ризик піддатися спокусам або самообману.', upright_en: 'A wide range of choices, but most options are illusions or fantasies. The risk of succumbing to temptations or self-deception.', reversed: 'Прояснення ілюзій, тверезий погляд на ситуацію або подолання залежності.', reversed_en: 'Dispelling illusions, a sober look at the situation, or overcoming an addiction.' },
        { upright: 'Людина залишає те, що раніше було цінним, і вирушає на пошуки глибшого духовного сенсу.', upright_en: 'A person leaves what was once valuable and sets out in search of deeper spiritual meaning.', reversed: 'Нездатність відпустити минуле, страх самотності або поверхнє задоволення замість справжнього пошуку.', reversed_en: 'An inability to let go of the past, fear of loneliness, or superficial satisfaction instead of a genuine search.' },
        { upright: '"Карта бажань". Повний комфорт, виконання матеріальних чи емоційних забаганок, гордість за себе.', upright_en: '"The wish card." Complete comfort, fulfillment of material or emotional desires, and pride in oneself.', reversed: 'Ненаситність, пошук задоволень без сенсу або матеріалізм, що спустошує душу.', reversed_en: 'Insatiability, a search for pleasure without meaning, or materialism that empties the soul.' },
        { upright: 'Абсолютна гармонія в родині, міцний шлюб, благополуччя, відчуття безпеки та єднання з близькими.', upright_en: 'Absolute harmony in the family, a strong marriage, well-being, and a sense of security and unity with loved ones.', reversed: 'Руйнація сімейного благополуччя, напруга в стосунках або втрата домашнього затишку.', reversed_en: 'The breakdown of family well-being, tension in relationships, or the loss of domestic comfort.' },
        { upright: 'Пропозиція руки та серця, примирення, зародження симпатії, творчий імпульс від чистого серця.', upright_en: 'A marriage proposal, reconciliation, the birth of affection, and a creative impulse from a pure heart.', reversed: 'Маніпуляції під маскою доброти, незрілість або емоційна нестабільність.', reversed_en: 'Manipulation under a mask of kindness, immaturity, or emotional instability.' },
        { upright: 'Приїзд коханої людини, романтичний жест, щира пропозиція. Людина, яка керується емоціями.', upright_en: 'The arrival of a loved one, a romantic gesture, and a sincere offer. A person who is guided by emotions.', reversed: 'Занадто ідеалістичний погляд на стосунки, розчарування або нереалізовані мрії.', reversed_en: 'An overly idealistic view of relationships, disappointment, or unrealized dreams.' },
        { upright: 'Любляча, чуйна жінка з розвиненою інтуїцією. Хороший психолог, вірна подруга чи турботлива мати.', upright_en: 'A loving, sensitive woman with developed intuition. A good psychologist, a faithful friend, or a caring mother.', reversed: 'Надмірна опіка, емоційна залежність або нездатність тверезо мислити.', reversed_en: 'Overprotection, emotional dependency, or an inability to think clearly.' },
        { upright: 'Емоційно зрілий, дипломатичний чоловік. Він вміє контролювати почуття, дає мудрі поради та підтримує.', upright_en: 'An emotionally mature, diplomatic man. He knows how to control his feelings, gives wise advice, and offers support.', reversed: 'Емоційна нестабільність, маніпуляції або залежна поведінка.', reversed_en: 'Emotional instability, manipulation, or dependent behavior.' }
    ],

    // ── МЕЧІ (Повітря) ───────────────────────────────────────────────────────
    s: [
        { upright: 'Інсайт, прийняття жорсткого, але правильного рішення. Розсікання сумнівів, перемога розуму.', upright_en: 'Insight, making a tough but correct decision. Cutting through doubts and the triumph of the mind.', reversed: 'Жорстокість, несправедливе рішення або нездатність думати ясно.', reversed_en: 'Cruelty, an unjust decision, or an inability to think clearly.' },
        { upright: 'Людина заплющує очі на проблеми. Необхідність зробити вибір у ситуації, коли бракує інформації.', upright_en: 'A person closes their eyes to problems. The need to make a choice in a situation where information is lacking.', reversed: 'Вихід із безвиході, готовність поглянути правді у вічі або розкриття обману.', reversed_en: 'Escaping a deadlock, readiness to face the truth, or the exposure of deception.' },
        { upright: 'Горе, душевна рана, розчарування в коханні або дружбі. Проте це необхідне очищення через правду.', upright_en: 'Grief, a soul wound, disappointment in love or friendship. However, this is a necessary cleansing through truth.', reversed: 'Прийняття болю, початок зцілення або вихід із горя.', reversed_en: 'Acceptance of pain, the beginning of healing, or emerging from grief.' },
        { upright: 'Тимчасова пауза, відпустка, госпіталізація або медитація. Час для відновлення ментальних сил.', upright_en: 'A temporary pause, vacation, hospitalization, or meditation. Time to restore mental strength.', reversed: 'Нездатність відпочити, надмірна активність або кризовий стан через виснаження.', reversed_en: 'An inability to rest, excessive activity, or a crisis due to exhaustion.' },
        { upright: 'Важкий конфлікт. Ви можете перемогти, але ціна буде занадто високою (втрата стосунків, репутації).', upright_en: 'A difficult conflict. You may win, but the price will be too high (loss of relationships or reputation).', reversed: 'Вихід із деструктивного конфлікту, примирення або уникнення безглуздого протистояння.', reversed_en: 'Escaping a destructive conflict, reconciliation, or avoiding a senseless confrontation.' },
        { upright: 'Рух до кращих часів. Подорож, зміна роботи чи місця проживання, відхід від важких обставин.', upright_en: 'Moving toward better times. Travel, changing jobs or place of residence, and retreating from difficult circumstances.', reversed: 'Нездатність вирватися з важкої ситуації або повторення старих помилок.', reversed_en: 'An inability to break free from a difficult situation or the repetition of old mistakes.' },
        { upright: 'Обхідні шляхи, шпигунство, крадіжка (інформації чи речей). Потреба діяти нестандартно чи потаємно.', upright_en: 'Detours, spying, theft (of information or objects). The need to act in an unconventional or secretive way.', reversed: 'Викриття обману, повернення вкраденого або відмова від нечесної тактики.', reversed_en: 'Exposure of deception, the return of something stolen, or abandonment of dishonest tactics.' },
        { upright: 'Людина зв\'язана по руках і ногах, але ці обмеження — лише в її голові. Страх зробити крок.', upright_en: 'A person is bound hand and foot, but these limitations exist only in their mind. Fear of taking a step.', reversed: 'Усвідомлення своєї сили, звільнення від внутрішніх обмежень або вихід із пастки.', reversed_en: 'Awareness of one\'s strength, liberation from inner limitations, or escaping a trap.' },
        { upright: 'Сильні переживання, панічні атаки, почуття провини. Страхи, які сильно перебільшені у вашій уяві.', upright_en: 'Intense anxiety, panic attacks, and feelings of guilt. Fears that are greatly exaggerated in your imagination.', reversed: 'Поступове подолання тривоги, робота з психологом або вихід із нічного кошмару.', reversed_en: 'Gradually overcoming anxiety, working with a psychologist, or escaping a nightmare.' },
        { upright: 'Остаточне завершення важкого етапу. Болісний кінець ситуації, після якого можливе тільки відродження.', upright_en: 'The final conclusion of a difficult phase. A painful end to a situation, after which only rebirth is possible.', reversed: 'Прийняття неминучого кінця, початок відновлення або вихід із найглибшої кризи.', reversed_en: 'Accepting an inevitable end, the start of recovery, or emerging from the deepest crisis.' },
        { upright: 'Інтелектуальна допитливість, збір пліток чи фактів, дрібні суперечки. Настороженість і шпигунство.', upright_en: 'Intellectual curiosity, gathering gossip or facts, and minor disputes. Vigilance and spying.', reversed: 'Жорстка критика, поверхневе мислення або розповсюдження чуток.', reversed_en: 'Harsh criticism, superficial thinking, or spreading rumors.' },
        { upright: 'Гострий конфлікт, різкі зміни, інтелектуальний штурм. Людина діє швидко, холодно і безжально.', upright_en: 'A sharp conflict, abrupt changes, and an intellectual assault. A person who acts quickly, coldly, and ruthlessly.', reversed: 'Жорстокість, деструктивна критика або хаотична агресія.', reversed_en: 'Cruelty, destructive criticism, or chaotic aggression.' },
        { upright: 'Розумна, сувора, незалежна жінка. Часто вказує на професіонала (юрист, лікар) або на самотню жінку.', upright_en: 'An intelligent, strict, independent woman. Often indicates a professional (lawyer, doctor) or a single woman.', reversed: 'Холодність, злопам\'ятність або надмірна критичність стосовно інших.', reversed_en: 'Coldness, vindictiveness, or excessive criticism of others.' },
        { upright: 'Холодний, авторитетний чоловік-інтелектуал. Суддя, військовий, керівник. Керується суто логікою.', upright_en: 'A cold, authoritative male intellectual. A judge, a military officer, a leader. Guided purely by logic.', reversed: 'Тиранія, жорстока справедливість або маніпуляції через знання.', reversed_en: 'Tyranny, cruel justice, or manipulation through knowledge.' }
    ],

    // ── ПЕНТАКЛІ (Земля) ─────────────────────────────────────────────────────
    p: [
        { upright: 'Велика удача, фінансовий успіх, отримання премії, спадщини або чудової бізнес-можливості.', upright_en: 'Great luck, financial success, receiving a bonus, inheritance, or a wonderful business opportunity.', reversed: 'Упущена матеріальна можливість, фінансова невдача або надмірний матеріалізм.', reversed_en: 'A missed material opportunity, financial failure, or excessive materialism.' },
        { upright: 'Балансування між двома справами або фінансовими зобов\'язаннями. Легке ставлення до грошей і змін.', upright_en: 'Balancing between two matters or financial obligations. A relaxed attitude towards money and changes.', reversed: 'Фінансова непослідовність, невміння керувати грошима або надмірна напруга.', reversed_en: 'Financial inconsistency, inability to manage money, or excessive stress.' },
        { upright: 'Визнання професіоналізму, успішна командна праця, будівництво, перші заробітки від улюбленої справи.', upright_en: 'Recognition of professionalism, successful teamwork, construction, and first earnings from a beloved pursuit.', reversed: 'Проблеми з командою, відсутність визнання або низька якість роботи.', reversed_en: 'Team problems, lack of recognition, or poor quality of work.' },
        { upright: 'Утримання ресурсів, страх втратити накопичене. Фінансова стабільність, але повна відсутність розвитку.', upright_en: 'Holding onto resources and fear of losing what has been accumulated. Financial stability, but a complete absence of growth.', reversed: 'Марнотратство, відкидання скупості або готовність до нових інвестицій.', reversed_en: 'Wastefulness, rejection of miserliness, or readiness for new investments.' },
        { upright: 'Фінансові труднощі, почуття самотності, духовна чи матеріальна бідність. Потреба просити про допомогу.', upright_en: 'Financial difficulties, a feeling of loneliness, and spiritual or material poverty. The need to ask for help.', reversed: 'Вихід із фінансових труднощів, подолання ізоляції або знаходження підтримки.', reversed_en: 'Emerging from financial difficulties, overcoming isolation, or finding support.' },
        { upright: 'Допомога іншим або отримання кредиту/дотації. Справедливий розподіл ресурсів, меценатство.', upright_en: 'Helping others or receiving a loan/grant. A fair distribution of resources and patronage.', reversed: 'Корупція, нечесний розподіл ресурсів або неправильно спрямована щедрість.', reversed_en: 'Corruption, unfair distribution of resources, or misdirected generosity.' },
        { upright: 'Урожай зріє повільно. Період, коли треба проявити терпіння і не квапити події, робота на перспективу.', upright_en: 'The harvest is ripening slowly. A period when one must show patience and not rush events, working for the future.', reversed: 'Нетерплячість, передчасна відмова від зусиль або незадоволеність результатами.', reversed_en: 'Impatience, premature abandonment of efforts, or dissatisfaction with results.' },
        { upright: 'Щоденна сумлінна праця, відточування майстерності. Крок за кроком ви створюєте свій успіх.', upright_en: 'Daily diligent work and honing mastery. Step by step, you are creating your success.', reversed: 'Перфекціонізм, рутина, що пригнічує, або відсутність прогресу попри зусилля.', reversed_en: 'Perfectionism, oppressive routine, or a lack of progress despite efforts.' },
        { upright: 'Матеріальна незалежність, безпека, вміння насолоджуватися життям. Достаток, який ви заробили самі.', upright_en: 'Material independence, security, and the ability to enjoy life. Prosperity that you have earned yourself.', reversed: 'Самовдоволення, надмірна залежність від матеріального або втрата здобутків.', reversed_en: 'Complacency, excessive dependence on material things, or the loss of gains.' },
        { upright: 'Фінансове процвітання сім\'ї, стабільний великий бізнес, традиції, сімейні цінності та підтримка рідних.', upright_en: 'The financial prosperity of the family, a stable large business, traditions, family values, and the support of relatives.', reversed: 'Сімейні фінансові суперечки, небезпечна залежність від родини або втрата спадщини.', reversed_en: 'Family financial disputes, dangerous dependence on family, or the loss of inheritance.' },
        { upright: 'Перші невеликі гроші, студентство, практична пропозиція, закладання фундаменту для майбутніх доходів.', upright_en: 'First small earnings, student life, a practical offer, and laying the foundation for future income.', reversed: 'Безвідповідальність, ухилення від навчання або нереалістичні фінансові плани.', reversed_en: 'Irresponsibility, avoidance of learning, or unrealistic financial plans.' },
        { upright: 'Найнадійніша карта. Повільний, але гарантований рух до мети, прагматизм, працьовитість, затишок.', upright_en: 'The most reliable card. Slow but guaranteed movement towards a goal, pragmatism, hard work, and coziness.', reversed: 'Надмірна консервативність, лінощі або застій через страх ризику.', reversed_en: 'Excessive conservatism, laziness, or stagnation due to a fear of risk.' },
        { upright: 'Практична, щедра, успішна жінка. Вона вміє створювати комфорт, керувати бюджетом і піклуватися про дім.', upright_en: 'A practical, generous, successful woman. She knows how to create comfort, manage a budget, and care for the home.', reversed: 'Надмірна опіка в матеріальному, скупість або невміння встановлювати фінансові кордони.', reversed_en: 'Excessive material overprotection, miserliness, or an inability to set financial boundaries.' },
        { upright: 'Багатий, досвідчений чоловік, успішний бізнесмен або фінансист. Символізує надійність та матеріальну владу.', upright_en: 'A wealthy, experienced man, a successful businessman or financier. Symbolizes reliability and material authority.', reversed: 'Жадібність, корупція або використання матеріальних ресурсів для маніпуляцій.', reversed_en: 'Greed, corruption, or the use of material resources for manipulation.' }
    ]
};
